Add ImageVector support to the preference datastore ui
patrickgold/jetpref pull request #2
Opened 2024-03-26 22:04 UTC by lm41

I need this to fully switch to ImageVectors in the https://github.com/florisboard/florisboard project. 

The old method of using Drawable Ids is still supported. Consideration may be given to deprecating these methods.

2024-03-26 23:44 UTC, patrickgold requested changes
Thanks a lot for the changes.

I have reviewed them and am currently a bit torn apart about the way you've implemented the image vector support. What if we take a bit of convenience away from the composables and only expose the following attributes:

```
icon: @Composable (() -> Unit)? = null,
iconSpaceReserved: Boolean,
```

on each composable that has an icon? Basically we (almost) eliminate the need for maybeJetIcon, we only need the `({ })` composable if iconSpaceReserved=true. What we definitely save is duplication of all composables which reduces maintainability issues going on. In the FlorisBoard code base we can introduce a convenience function which makes an icon composable from a drawable id or an ImageVector. Would also solve the awkward need to specify imageVector=null on the composable if I see it correctly.

You do not need to mark any of the old functions as deprecated as jetpref has not had any stable release yet so breaking API changes are expected.

2024-03-27 14:44 UTC, lm41 commented
I've thought about it a bit and I think I've found a good option via the JetIcon interface. 
This also enables additional support for your own icon implementations (such as custom painter etc.)

2024-03-27 19:02 UTC, patrickgold requested changes
Thanks a lot for the changes! I've had a look at the changes and like the JetIcon idea! There are some issues/questions though that need clarification or fixing. (See comments)

2024-03-27 19:06 UTC, lm41 commented on datastore-ui/src/main/kotlin/dev/patrickgold/jetpref/datastore/ui/JetIcon.kt
Thanks :)

2024-03-27 21:17 UTC, lm41 commented on gradle/libs.versions.toml
> +androidx-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-material-icons" }
Yeah thats a mistake. I should've used `material-icons`. 
But FYI: https://stackoverflow.com/questions/71383235/jetpack-compose-remove-material-icons-extended-unused-icon#comment126180987_71383235
You do not need to use proguard if you have minify enabled in release builds

2024-03-27 21:18 UTC, lm41 commented on datastore-ui/src/main/kotlin/dev/patrickgold/jetpref/datastore/ui/DialogSliderPreference.kt
> +            icon = icon?.getIcon(iconSpaceReserved),
I'll have to look into this.

2024-03-27 21:30 UTC, lm41 commented on datastore-ui/src/main/kotlin/dev/patrickgold/jetpref/datastore/ui/DialogSliderPreference.kt
> +            icon = icon?.getIcon(iconSpaceReserved),
I've pushed a fix :grinning:

2024-03-27 23:42 UTC, patrickgold commented on gradle/libs.versions.toml
> +androidx-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-material-icons" }
good to know!

2024-03-27 23:51 UTC, patrickgold requested changes
Thanks for the fix, I've re-reviewed your incoming changes. After this iteration I think the code should be ready to merge

2024-03-27 23:51 UTC, patrickgold commented on datastore-ui/src/main/kotlin/dev/patrickgold/jetpref/datastore/ui/JetIcon.kt
> +    override fun getIcon(iconSpaceReserved: Boolean): @Composable() (() -> Unit)? {
```suggestion
    override fun getIcon(iconSpaceReserved: Boolean): @Composable (() -> Unit)? {
```

(format nitpick)

2024-03-27 23:51 UTC, patrickgold commented on datastore-ui/src/main/kotlin/dev/patrickgold/jetpref/datastore/ui/JetIcon.kt
> +    get() = if(this == null) { EmptyIcon } else { DrawableResIcon(this) }
```suggestion
    get() = if (this == null) { EmptyIcon } else { DrawableResIcon(this) }
```

(format nitpick)

2024-03-27 23:51 UTC, patrickgold commented on gradle/libs.versions.toml
> +androidx-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-material-icons" }
Anyways in our case should the non-extended lib be used here or is the extended required?

2024-03-27 23:51 UTC, patrickgold commented on datastore-ui/src/main/kotlin/dev/patrickgold/jetpref/datastore/ui/JetIcon.kt
Could you please add documentation to the JetIcon interface and shorthands using the docstring format from the composables? (for the version's since tag use 0.1.0)

2024-03-28 08:42 UTC, lm41 commented on gradle/libs.versions.toml
> +androidx-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-material-icons" }
`Icons.Default.Palette` is only included in the extended version :-)

2024-03-28 11:07 UTC, patrickgold approved these changes
Reviewed again and tested out locally, everything checks out fine, merging into main. Thanks for the efforts!

2024-03-28 11:09 UTC, patrickgold commented
For test using you'd have to use snapshots, here temporarily enable the jitpack repo in the core repo and then use the version table from [here](https://jitpack.io/#patrickgold/jetpref) to grab a snapshot version

2024-03-28 11:09 UTC, merged